name: Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy
      
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
      
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
          
    - uses: actions-rs/cargo@v1
      with:
        command: test
